#!/bin/bash
# Brave Web Search API
# https://api-dashboard.search.brave.com/app/documentation/web-search/get-started
# Query Parameters
# https://api-dashboard.search.brave.com/app/documentation/web-search/query#WebSearchAPIQueryParameters
export BRAVE_SEARCH_API_KEY=${BRAVE_SEARCH_API_KEY}
# Start of Selection
# Start of Selection
keyword=$(python -c "import urllib.parse; print(urllib.parse.quote('${1}'))")
curl -s --compressed "https://api.search.brave.com/res/v1/web/search?q=${keyword}" \
  -H "Accept: application/json" \
  -H "Accept-Encoding: gzip" \
  -H "X-Subscription-Token: ${BRAVE_SEARCH_API_KEY}"
# End of Selection