#!/bin/bash
# set temporary directory
TEMP_DIR=$(mktemp -d)
cd "$TEMP_DIR"
# set slackdump search
slackdump search messages "$1"
cd slackdump*
gunzip search.json.gz
cat search.json | jq --arg now "$(date +%s)" '
  if .sm then 
    .sm[:10] 
    | map(select(.username != null and .text != null and (.ts | tonumber) >= ($now | tonumber) - 604800)) 
    | map({channel_name: .channel.name, ts, username, text, permalink}) 
  else 
    empty 
  end'
cd ..
rm -rf slackdump*
