#!/bin/bash
export FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}

curl -X POST https://api.firecrawl.dev/v1/scrape \
    -H 'Content-Type: application/json' \
    -H 'Authorization: Bearer '${FIRECRAWL_API_KEY}'' \
    -d '{
      "url": "https://docs.firecrawl.dev",
      "formats" : ["markdown"]
    }'
